name: Bug Report
description: Report a bug to help us improve
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out the information below to help us resolve the issue quickly.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify that you have completed the following steps before submitting this bug report.
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before
          required: true
        - label: I have checked the documentation and FAQ for relevant information
          required: true
        - label: I am running the latest version of MCOP Framework
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      placeholder: |
        - OS: [e.g. macOS 14.0]
        - Browser: [e.g. Chrome 120.0]
        - Node.js version: [e.g. 18.17.0]
        - MCOP Framework version: [e.g. 2.0.0]
        - Package manager: [e.g. npm, yarn, pnpm]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error logs or console output
      placeholder: Paste error logs here...
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information...

  - type: checkboxes
    id: volunteer
    attributes:
      label: Would you like to contribute?
      description: Let us know if you'd like to help fix this bug
      options:
        - label: I would like to help fix this bug